modLoader="javafml"
loaderVersion="[47,)"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/Misaka2592/AE2ByproductRemover/issues"

[[mods]]
modId="ae2byproductremover"
version="${mod_version}"
displayName="AE2 Byproduct Remover"
displayURL="https://github.com/Misaka2592/AE2ByproductRemover"
authors="Misaka2592"
description='''Makes every processing-pattern output requestable and controls predicted output reuse.'''

[[dependencies.ae2byproductremover]]
modId="forge"
mandatory=true
versionRange="[47.4.16,48)"
ordering="NONE"
side="BOTH"

[[dependencies.ae2byproductremover]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.ae2byproductremover]]
modId="ae2"
mandatory=true
versionRange="[15.4.10]"
ordering="AFTER"
side="BOTH"
