modLoader="javafml"
loaderVersion="[4,)"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/Misaka2592/AE2ByproductRemover/issues"

[[mods]]
modId="ae2byproductremover"
version="${mod_version}"
displayName="AE2 Byproduct Remover"
displayURL="https://github.com/Misaka2592/AE2ByproductRemover"
authors="Misaka2592"
description='''Makes every processing-pattern output requestable and controls predicted output reuse.'''

[[mixins]]
config="ae2byproductremover.mixins.json"

[[mixins]]
config="ae2byproductremover.compat.mixins.json"

[[dependencies.ae2byproductremover]]
modId="neoforge"
type="required"
versionRange="[21.1.241,21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.ae2byproductremover]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.ae2byproductremover]]
modId="ae2"
type="required"
versionRange="[19.2.17]"
ordering="AFTER"
side="BOTH"
